# @package _group_
name: GCN
norm: true
loop: true
params:

  Cora:
    architecture:
      num_layers: 2
      hidden_channels: 16
      dropout: 0.5
      batch_norm: false
      residual: false
    num_parts: 40
    batch_size: 256
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 5e-4
    nonreg_weight_decay: 0
    grad_norm: 1.0
    epochs: 200
    runs: 10

  PubMed:
    architecture:
      num_layers: 2
      hidden_channels: 16
      dropout: 0.5
      batch_norm: false
      residual: false
    num_parts: 8
    batch_size: 256
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 5e-4
    nonreg_weight_decay: 0
    grad_norm: 1.0
    epochs: 200
    runs: 10

  CiteSeer:
    architecture:
      num_layers: 2
      hidden_channels: 16
      dropout: 0.5
      batch_norm: false
      residual: false
    num_parts: 24
    batch_size: 256
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 5e-4
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 200
    runs: 10

  reddit:
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.5
      drop_input: false
      batch_norm: false
      residual: false
    num_parts: 200
    batch_size: 256
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0.0
    nonreg_weight_decay: 0.0
    grad_norm: none
    epochs: 400
    runs: 10

  flickr:
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.3
      drop_input: true
      batch_norm: false
      residual: false
    num_parts: 24
    batch_size: 256
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 400
    runs: 10

  arxiv:
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.5
      drop_input: false
      batch_norm: false
      residual: false
    num_parts: 80
    batch_size: 256
    max_steps: 2
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: none
    epochs: 300
    runs: 10

  yelp:
    architecture:
      num_layers: 2
      hidden_channels: 512
      dropout: 0.0
      drop_input: false
      batch_norm: false
      residual: false
      linear: false
    num_parts: 40
    batch_size: 256
    max_steps: 4
    pool_size: 2
    num_workers: 0
    lr: 0.01
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 500
    runs: 10

  products:
    architecture:
      num_layers: 2
      hidden_channels: 256
      dropout: 0.3
      drop_input: false
      batch_norm: false
      residual: false
    num_parts: 7
    batch_size: 256
    max_steps: 4
    pool_size: 1
    num_workers: 0
    lr: 0.005
    reg_weight_decay: 0
    nonreg_weight_decay: 0
    grad_norm: null
    epochs: 300
    runs: 10
